### ISSUE TITLE
Files not deleting

### ISSUE THREAD

**Issue by basham** [callumacrae/rev-del#2]
Can you confirm that the plugin works? I'm using:

`gulp-rev` version 3.0.1
`rev-del` version 1.0.3

``` js
// rev.js
var gulp = require('gulp');
var rev = require('gulp-rev');
var revDel = require('rev-del');

gulp.task('rev', function() {
  return gulp.src([
      './build/**/{bundle.css,scripts.js,vendor.js}'
    ])
    .pipe(rev())
    .pipe(gulp.dest('./build'))
    .pipe(rev.manifest())
    .pipe(revDel({}, function(err, filesDeleted) {
      console.log('del', err, filesDeleted)
    }))
    .pipe(gulp.dest('./build'));
});
```

`rev()` works fine, but no previously generated files are deleted. I'm getting no output from `console.log()` in the callback.

**Comment by callumacrae** [comment]
I'm getting the same issue here—weird, because the tests are working fine.

I'll have a look into this soon.

**Comment by callumacrae** [comment]
![screen shot 2015-02-19 at 18 38 51](https://cloud.githubusercontent.com/assets/472830/6273337/953dc878-b866-11e4-8df0-4677e6d06b2f.png)

**Comment by callumacrae** [comment]
Okay, try making two changes to your code: add a `dest` option containing './build', and remove the callback—that only works when you're calling `revDel` directly.

``` js
var gulp = require('gulp');
var rev = require('gulp-rev');
var revDel = require('rev-del');

gulp.task('rev', function() {
  return gulp.src([
      './build/**/{bundle.css,scripts.js,vendor.js}'
    ])
    .pipe(rev())
    .pipe(gulp.dest('./build'))
    .pipe(rev.manifest())
    .pipe(revDel({ dest: './build' }))
    .pipe(gulp.dest('./build'));
});
```

**Comment by basham** [comment]
The `v1.0.4` update works for me.

By the way, this was my temporary fix:

``` js
var gulp = require('gulp');
var del = require('del');
var rev = require('gulp-rev');

gulp.task('rev-del', function(callback) {
  del(['./build/**/{bundle-*.css,scripts-*.js,vendor-*.js}'], callback);
});

gulp.task('rev', ['rev-del'], function() {
  return gulp.src([
      './build/**/{bundle.css,scripts.js,vendor.js}'
    ])
    .pipe(rev())
    .pipe(gulp.dest('./build'))
    .pipe(rev.manifest())
    .pipe(gulp.dest('./build'));
});
```

The plugin is much nicer. Thanks!

**Comment by callumacrae** [comment]
That approach isn't so great if you're using something like gulp-changed, though! Glad it's working now.

**Comment by basham** [comment]
I watch, build, and inject `bundle.css`, `scripts.js`, and `vendor.js` files for development. Then those files are being watched, which will trigger the `rev` task. I'm not directly using the `rev` output; those are only for production. So, I avoid the problem you're alluding to.

**Comment by callumacrae** [comment]
Fair enough. I mostly use this plugin for images, so I use gulp-changed—if I removed them every time, my build would take ages!
