### ISSUE TITLE
Files not deleting (redux)

### ISSUE THREAD

**Issue by rich-glow** [callumacrae/rev-del#3]
I have the following task:

``` js
var DIR_BUILD = './build';
gulp.task('revFiles', function() {
    return gulp.src(['deps.min.js', 'app.min.js', 'app.min.css'], {cwd: DIR_BUILD})
        .pipe(rev())
        .pipe(gulp.dest(DIR_BUILD))
        .pipe(rev.manifest())
        .pipe(revDel({dest: DIR_BUILD}))
        .pipe(gulp.dest(DIR_BUILD));
});
```

but it does not delete the older files.

Im using version `1.0.4`

This issue looks the same as [this issue](https://github.com/callumacrae/rev-del/issues/2), but it looks like the issue should be fixed in this version.

Am I missing something important in the task?

**Comment by hiddentao** [comment]
Same problem here

**Comment by callumacrae** [comment]
I can't replicate :disappointed: 

```
~/Sites/test
❯ ls build
a-258ff729.txt    a.txt             b-d8e8fca2.txt    b.txt             rev-manifest.json

~/Sites/test
❯ echo 'test' >> build/a.txt

~/Sites/test
❯ echo 'test' >> build/b.txt

~/Sites/test
❯ gulp
[10:32:15] Using gulpfile ~/Sites/test/gulpfile.js
[10:32:15] Starting 'default'...
[10:32:15] Finished 'default' after 37 ms

~/Sites/test
❯ ls build
a-45bbdb2e.txt    a.txt             b-683f7548.txt    b.txt             rev-manifest.json
```

I'm using basically the same gulpfile as you:

```
gulp.task('default', function() {
    return gulp.src(['a.txt', 'b.txt'], { cwd: './build' })
        .pipe(rev())
        .pipe(gulp.dest('./build'))
        .pipe(rev.manifest())
        .pipe(revDel({ dest: './build' }))
        .pipe(gulp.dest('./build'));
});
```

Would you be able to contribute a failing test case, or set up a repo I can replicate this in?

**Comment by callumacrae** [comment]
Also what environment are you guys using? I've only tested it on OS X and Ubuntu.

**Comment by rich-glow** [comment]
Thanks for taking a look.

running ubuntu. I will strive to create a repo/test.

**Comment by rich-glow** [comment]
huh, works for me now. Really odd. Lets chalk this up to user error.

Thanks.

**Comment by callumacrae** [comment]
Cool. @hiddentao are you still having problems?

**Comment by hiddentao** [comment]
@callumacrae Yeah I couldn't solve it, so I now just delete the files myself using `del` before running `gulp-rev`. That works well enough for me.

**Comment by falzhobel** [comment]
@callumacrae Also have the same problem, here's my task:

```
gulp.task('cachebust', function() {
  return gulp.src([
      'public/assets/css/**.*',
      'public/assets/js/**.*'
    ], {
      base: path.join(__dirname, '/public/assets')
    })
    .pipe(rev())
    .pipe(gulp.dest('./public/assets'))
    .pipe(rev.manifest())
    .pipe(revDel())
    .pipe(gulp.dest('./public/assets'));
});
```

**Comment by jovinbm** [comment]
I can't get the plugin to delete old files. I have the following task

``` javascript
gulp.task('aboutScss', function () {
    var name = 'aboutScss';
    var paths = [
        'public/css/pages/about/**/*.scss',
    ];
    var options = {
        extensions: ["css, !less", "!sass"]
    };
    return gulp.src(paths)
        .pipe(sourcemaps.init())
        .pipe(sass().on('error', sass.logError))
        .pipe(minifyCss())
        .pipe(sourcemaps.write('.'))
        .pipe(ext_replace('.min.css'))
        .pipe(gulp.dest('public/cssmin/about'))
        .pipe(rev())
        .pipe(gulp.dest('public/cssmin/about'))
        .pipe(rev.manifest(name + '.json'))
        ..pipe(revDel({
            dest: './public/assetsManifests',
            base: './public/cssmin/about',
            suppress: false
        }))
        .pipe(gulp.dest('public/assetsManifests'));
});
```

Old files still stick around. Am I missing something?

**Comment by jovinbm** [comment]
Okay, so updating https://github.com/callumacrae/rev-del/blob/master/index.js#L29 to the following worked for me.

``` javascript
return path.join(options.base || options.dest, file);
```

The reason I did this was in my case, each gulp task saved it's own manifest file under a unique name in the `./public/assetsManifests` folder. These are then later combined into one. The `dest` was where the manifests were available, the `base` was where the assets were found. The original code used `dest` instead of `base` to get the full asset path hence not finding the old assets.

**Comment by TangMonk** [comment]
it is confused, how about change `base` to `assetPath` and `dest` to `manifestPath`
