### ISSUE TITLE
Usage into gulp-usemin, files are not deleting

### ISSUE THREAD

**Issue by thisfrontenddev** [callumacrae/rev-del#8]
My point is that I want to remove unused files generated by `gulp-rev` package. Here is my directory structure.

```
/source
    /views
    /static
        /css
        /js
/build
    /views
    /static
        /css
        /js
gulpfile.js
```

I'm using the `gulp-usemin` plugin as I said and I can't get the old revision-ed files deleted.

Here is the example given in the documentation

```
gulp.task('default', function () {
return gulp.src('src/*.css')
    .pipe(rev())
    .pipe(gulp.dest('dist'))
    .pipe(rev.manifest())
    .pipe(revDel({ dest: 'dist' }))
    .pipe(gulp.dest('dist'));
});
```

Here is my task, using `gulp-usemin` and `rev-del` packages :

```
var SRC_SASS_FILES_PATH = 'source/static/sass';
var SRC_CSS_FILES_PATH = 'source/static/css';
var SRC_VIEWS_PATH = 'source/views';
var BUILD_CSS_PATH = 'build/static/css';
var BUILD_JS_PATH = 'build/static/js';
var BUILD_VIEWS_PATH = 'build/views';


gulp.task('usemin', function() {

    return gulp.src(SRC_VIEWS_PATH + '/*.html')
    .pipe(usemin({
        css: [ rev() ],
        js: [
            function(){ return uglify(); },
            function(){ return rev() },
            function(){ return rev.manifest() },
            function(){ return revDel({ dest:BUILD_JS_PATH }) },
        ]
    }))
    .pipe(gulp.dest(BUILD_VIEWS_PATH))
});
```

I cant get my JS files deleted for those that are old revision-ed files. Tried to output errors with the second parameter callback of revDel but no errors at all. Commands run fine but doesn't seem to be working.

I looked all over SO, github issues but I was not able to find anything about this. Usemin should be able to return the current file stream used at the moment but I still cannot get these files deleted. I feel like revDel is still using the filestream from `gulp.src(SRC_VIEWS_PATH + '/*.html')`, despite the `dest` option that I manually set.

Any ideas of what's going on there ?
`rev-del` version `1.0.5`.

**Comment by callumacrae** [comment]
Hey, did you solve this issue?

**Comment by thisfrontenddev** [comment]
No, unfortunately. I'm not on this project anymore though (previous company project), so this can be closed as not resolved.

Thanks

**Comment by callumacrae** [comment]
Alright. Sorry about that.
